app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/login');
});

// Daftar Route
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@postRegister');

//Login Route
Route::get('/login', 'AuthController@login');
Route::post('/handleLogin', 'AuthController@handleLogin');
Route::get('/logout', 'AuthController@logout');

// Reset Password
Route::get('password/reset/{token?}', 'PasswordController@showResetForm');
Route::post('password/email', 'PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'PasswordController@reset');
Route::get('formatid', 'PesanController@pesanID');


Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', 'HomeController@index');
	Route::get('/profil', 'HomeController@profil');
	Route::post('/foto_profil', 'AuthController@foto_profil');
	Route::get('/ubah_profil', 'HomeController@ubah_profil');
	Route::post('/update_profil', 'HomeController@update_profil');
	Route::post('/gantipassword', 'AuthController@gantipassword');
	Route::get('/detail/{detail}', 'HomeController@detail_kost');
	Route::get('/listkost/{gender}', 'HomeController@listkost');
	Route::post('/testimoni', 'HomeController@testimoni');
	Route::delete('/testimoni', 'HomeController@hapusTestimoni');
	Route::get('/addkost', 'PemilikController@add_mykost');
	Route::get('/unduh', 'HomeController@unduh');
	/* ---ADMINISTRATOR--- */
	Route::group(['middleware' => 'role:admin'], function() 
	{
		Route::get('/admin', 'AdminController@beranda');
		
		/* ---PARAMETER/VARIABEL ROUTE--- */
		Route::get('/parameter','ParameterController@index');
		Route::post('/parameter','ParameterController@store');
		Route::put('/parameter','ParameterController@update');
		Route::delete('/parameter','ParameterController@destroy');

		/* ---HIMPUNAN ROUTE--- */
		Route::get('/himpunan','HimpunanController@index');
		Route::post('/himpunan','HimpunanController@store');
		Route::put('/himpunan','HimpunanController@update');
		Route::delete('/himpunan','HimpunanController@destroy');

		/* ---DERAJAT KEANGGOTAAN ROUTE--- */
		Route::get('/derajat','DerajatController@index');
		Route::get('/derajat/generate','DerajatController@generate');

		/* ---PENGGUNA ROUTE--- */
		Route::get('/pengguna/{level}', 'UserController@user');
		Route::resource('/user','UserController');
		Route::delete('/user','UserController@destroy');

		/* ---KOSTAN ROUTE--- */
		Route::resource('/kost','KostController');
		Route::delete('/kost','KostController@destroy');
		Route::post('/carikost','KostController@carikost');

		/* ---PEMESANAN ROUTE--- */
		Route::get('/pesan','PesanController@index');
	});

	/* ---PEMILIK--- */
	Route::group(['middleware' => 'role:pemilik'], function() 
	{
		Route::get('/kostsaya', 'PemilikController@kostsaya');
		Route::post('/storekost', 'PemilikController@storekost');
		Route::get('/lengkapi/{kost}', 'PemilikController@lengkapi');
		Route::post('/lengkapi', 'PemilikController@postlengkapi');
		Route::get('/ubahkriteria/{id}', 'PemilikController@ubahkriteria');
		Route::get('/edit_kost/{id}', 'PemilikController@edit_kost');
		Route::post('/update_kost', 'PemilikController@update_kost');
		Route::delete('/hapuskost', 'PemilikController@hapuskost');
	});

	/* ---MAHASISWA--- */
	Route::group(['middleware' => 'role:mahasiswa|admin'], function()
	{
		Route::post('/cari', 'HomeController@cari');
		Route::get('/pencarian', 'HomeController@pencarian');
		Route::post('/pesan','PesanController@store');
		Route::get('/pesan/{id}','PesanController@show');
		Route::delete('/pesan','PesanController@destroy');
	});

});

app/Kost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kost extends Model
{
    public function user()
	{
		return $this->belongsTo('App\User', 'user_id');
	}

	public function relasi()
    {
    	return $this->hasMany('App\Relasi', 'id_kost');
    }

    public function testimoni()
    {
        return $this->hasMany('App\Testimoni', 'kost_id');
    }

    public function derajat()
    {
        return $this->hasMany('App\Derajat', 'kost_id');
    }

    public function pesan()
    {
        return $this->hasMany('App\Pesan', 'kost_id');
    }

}

app/Http/Controllers/KostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kost;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Image;
use App\Http\Requests;
use File;

class KostController extends Controller
{
    public function index() {
		$kost = Kost::all();
		return view('kost.index', compact('kost'));
	}

	public function create()
	{
		return view('kost.create');
	}

    public function store(Request $request)
	{
		$this->validate($request, [
            'nama_kost' => 'required',
            'jenis_kost' => 'required|min:1',
            'kamar_mandi' => 'required|min:1',
            'jumlah_kamar' => 'required',
            'alamat_kost' => 'required',
            'deskripsi' => 'required',
            'foto_1' => 'required|mimes:jpeg,jpg,png|max:1520',
            'foto_2' => 'required|mimes:jpeg,jpg,png|max:1520',
            'foto_3' => 'required|mimes:jpeg,jpg,png|max:1520',
            'foto_4' => 'required|mimes:jpeg,jpg,png|max:1520',
        ]);

		$kost = new Kost();
        $kost->user_id = Auth::user()->id;
        $nama = Auth::user()->nama_depan;
        $kost->nama_kost = Input::get('nama_kost');
        $kost->jenis_kost = Input::get('jenis_kost');
        $kost->kamar_mandi = Input::get('kamar_mandi');
        $kost->jumlah_kamar = Input::get('jumlah_kamar');
        $kost->sisa_kamar = preg_replace('/\D/','',Input::get('jumlah_kamar'));
        $kost->alamat_kost = Input::get('alamat_kost');
        $kost->deskripsi = Input::get('deskripsi');
        $kost->status = ('Proses');

        $foto_1 = Input::file('foto_1');
        $foto_2 = Input::file('foto_2');
        $foto_3 = Input::file('foto_3');
        $foto_4 = Input::file('foto_4');
        
        $filename_1 = time().'1'.$nama.$kost->user_id.'.'.$foto_1->getClientOriginalExtension();
        $filename_2 = time().'2'.$nama.$kost->user_id.'.'.$foto_2->getClientOriginalExtension();
        $filename_3 = time().'3'.$nama.$kost->user_id.'.'.$foto_3->getClientOriginalExtension();
        $filename_4 = time().'4'.$nama.$kost->user_id.'.'.$foto_4->getClientOriginalExtension();

        $path_1 = public_path('kost_image/' . $filename_1);
        $path_2 = public_path('kost_image/' . $filename_2);
        $path_3 = public_path('kost_image/' . $filename_3);
        $path_4 = public_path('kost_image/' . $filename_4);
        
        Image::make($foto_1)->resize(320,240)->save($path_1);
        Image::make($foto_2)->resize(320,240)->save($path_2);
        Image::make($foto_3)->resize(320,240)->save($path_3);
        Image::make($foto_4)->resize(320,240)->save($path_4);
        
        $kost->foto_1 = $filename_1;
        $kost->foto_2 = $filename_2;
        $kost->foto_3 = $filename_3;
        $kost->foto_4 = $filename_4;

        $kost->save();

        if ($kost) {
            return redirect('/kost')->with('sukses', 'Berhasil menambah kost.');
        } else {
            return redirect('/kost')->with('gagal', 'Terjadi kesalahan saat menambah kost.');
        }

	}

	public function show($id) {
		$kost = Kost::find($id);
		return view('kost.view', compact('kost'));
	}

	public function edit($id) {
		$kost = Kost::find($id);
		return view('kost.update', compact('kost'));
	}

	public function update(Request $request ,$id) {
		
        $kost = Kost::find($id);

		$kost->nama_kost = Input::get('nama_kost');
        $kost->jenis_kost = Input::get('jenis_kost');
        $kost->kamar_mandi = Input::get('kamar_mandi');
        $kost->jumlah_kamar = Input::get('jumlah_kamar');
        $kost->sisa_kamar = Input::get('jumlah_kamar');
        $kost->alamat_kost = Input::get('alamat_kost');
        $kost->deskripsi = Input::get('deskripsi');
        $kost->status = Input::get('status');

        if (Input::hasFile('foto_1')) {
            File::delete('kost_image/' . $kost->foto_1);
            
            $foto_1 = Input::file('foto_1');
            $filename_1 = time().'1'.$kost->user_id.'.'.$foto_1->getClientOriginalExtension();
            $path_1 = public_path('kost_image/' . $filename_1);
            Image::make($foto_1)->resize(320,240)->save($path_1);
            $kost->foto_1 = $filename_1;
        }

        if (Input::hasFile('foto_2')) {
            File::delete('kost_image/' . $kost->foto_2);
            
            $foto_2 = Input::file('foto_2');
            $filename_2 = time().'2'.$kost->user_id.'.'.$foto_2->getClientOriginalExtension();
            $path_2 = public_path('kost_image/' . $filename_2);
            Image::make($foto_2)->resize(320,240)->save($path_2);
            $kost->foto_2 = $filename_2;
        }

        if (Input::hasFile('foto_3')) {
            File::delete('kost_image/' . $kost->foto_3);
            
            $foto_3 = Input::file('foto_3');
            $filename_3 = time().'3'.$kost->user_id.'.'.$foto_3->getClientOriginalExtension();
            $path_3 = public_path('kost_image/' . $filename_3);
            Image::make($foto_3)->resize(320,240)->save($path_3);
            $kost->foto_3 = $filename_3;
        }

        if (Input::hasFile('foto_4')) {
            File::delete('kost_image/' . $kost->foto_4);
            
            $foto_4 = Input::file('foto_4');
            $filename_4 = time().'4'.$kost->user_id.'.'.$foto_4->getClientOriginalExtension();
            $path_4 = public_path('kost_image/' . $filename_4);
            Image::make($foto_4)->resize(320,240)->save($path_4);
            $kost->foto_4 = $filename_4;
        }

		$kost->update();

		if ($kost) {
            return redirect('/kost')->with('sukses', 'Berhasil mengubah kost.');
        } else {
            return redirect('/kost')->with('gagal', 'Terjadi kesalahan saat mengubah kost.');
        }
	}

	public function destroy(Request $request) {
		$kost = Kost::find($request->id);

		unlink(public_path('kost_image/' . $kost->foto_1));
		unlink(public_path('kost_image/' . $kost->foto_2));
		unlink(public_path('kost_image/' . $kost->foto_3));
		unlink(public_path('kost_image/' . $kost->foto_4));

		$kost->delete();

        if ($kost) {
            return redirect('/kost')->with('sukses', 'Berhasil menghapus kost.');
        } else {
            return redirect('/kost')->with('gagal', 'Terjadi kesalahan saat menghapus kost.');
        }
	}

    public function carikost(Request $request) {
        $cari = Input::get('cari');
        $kost = Kost::where('nama_kost', 'like', '%'.$cari.'%')->get();
        return view('kost.index', compact('kost'));  
    }
}

resources/views/kost/create.blade.php
@extends('layouts.admin')

@section('content')
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Tambah Kost</strong> Isi identitas user
            </div>
            <div class="card-block">
                {!! Form::open(['route' => 'kost.store', 'files' => true, 'class' => 'form-horizontal'])!!}
                    <div class="col-sm-12">
                        <div class="form-group row {{ $errors->has('nama_kost') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="nama_kost">Nama Kost</label>
                            <div class="col-lg-9">
                                <input name="nama_kost" type="text" class="form-control" id="nama_kost" placeholder="Nama Kost" value="{{ old('nama_kost') }}">
                                @if ($errors->has('nama_kost'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('nama_kost') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row {{ $errors->has('jenis_kost') ? ' has-danger' : '' }}">
                        <label class="col-md-3 form-control-label" for="jenis_kost">Jenis Kost</label>
                            <div class="col-lg-9">
                                <select name="jenis_kost" class="form-control" id="jenis_kost" value="{{ old('jenis_kost') }}">
                                    <option>--Pilih jenis kost--</option>
                                    <option value="Pria" {{ (old('jenis_kost') == 'Pria' ? "selected":"") }} >Pria</option>
                                    <option value="Wanita"{{ (old('jenis_kost') == 'Wanita' ? "selected":"") }}>Wanita</option>
                                </select>
                                @if ($errors->has('jenis_kost'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('jenis_kost') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row {{ $errors->has('kamar_mandi') ? ' has-danger' : '' }}">
                        <label class="col-md-3 form-control-label" for="kamar_mandi">Jenis Kamar Mandi</label>
                            <div class="col-lg-9">
                                <select name="kamar_mandi" class="form-control" id="kamar_mandi">
                                    <option>--Pilih jenis kamar mandi--</option>
                                    <option value="Luar" {{ (old('kamar_mandi') == 'Luar' ? "selected":"") }}>Luar</option>
                                    <option value="Dalam" {{ (old('kamar_mandi') == 'Dalam' ? "selected":"") }}>Dalam</option>
                                </select>
                                @if ($errors->has('kamar_mandi'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('kamar_mandi') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row {{ $errors->has('jumlah_kamar') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="jumlah_kamar">Jumlah Kamar</label>
                            <div class="col-lg-9">
                                <input name="jumlah_kamar" type="text" class="form-control" id="jumlah_kamar" placeholder="Jumlah Kamar" value="{{ old('jumlah_kamar') }}">
                                @if ($errors->has('jumlah_kamar'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('jumlah_kamar') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('foto_1') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="foto_1">Foto Depan</label>
                            <div class="col-lg-9">
                                <input name="foto_1" type="file" class="form-control" id="foto_1" placeholder="Foto Depan" value="{{ old('foto_1') }}">
                                @if ($errors->has('foto_1'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('foto_1') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('foto_2') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="foto_2">Foto Kamar Kost</label>
                            <div class="col-lg-9">
                                <input name="foto_2" type="file" class="form-control" id="foto_2" placeholder="Foto Kamar Kost" value="{{ old('foto_2') }}">
                                @if ($errors->has('foto_2'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('foto_2') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('foto_3') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="foto_3">Foto Kamar Mandi</label>
                            <div class="col-lg-9">
                                <input name="foto_3" type="file" class="form-control" id="foto_3" placeholder="Foto Kamar Mandi" value="{{ old('foto_3') }}">
                                @if ($errors->has('foto_3'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('foto_3') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('foto_4') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="foto_4">Foto Pendukung</label>
                            <div class="col-lg-9">
                                <input name="foto_4" type="file" class="form-control" id="foto_4" placeholder="Foto Pendukung" value="{{ old('foto_4') }}">
                                @if ($errors->has('foto_4'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('foto_4') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('alamat_kost') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="alamat_kost">Alamat Kost</label>
                            <div class="col-lg-9">
                                <textarea  name="alamat_kost" class="form-control" rows="3" id="alamat_kost" placeholder="Alamat lengkap kost" >{{ old('alamat_kost') }}</textarea>
                                @if ($errors->has('alamat_kost'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('alamat_kost') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row{{ $errors->has('deskripsi') ? ' has-danger' : '' }}">
                            <label class="col-md-3 form-control-label" for="alamat_kost">Deskripsi Kost</label>
                            <div class="col-lg-9">
                                <textarea  name="deskripsi" class="form-control" rows="5" id="deskripsi" placeholder="Deskripsi kost">{{ old('deskripsi') }}</textarea>
                                @if ($errors->has('deskripsi'))
                                    <div class="form-control-feedback">
                                        {{ $errors->first('deskripsi') }}
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group row">
                            <div class="col-lg-9 col-lg-offset-2">
                                <button type="reset" class="btn btn-secondary"><i class="fa fa-chevron-left"> Batal</i></button>
                                <button type="submit" class="btn btn-success"><i class="fa fa-save"> Simpan</i></button>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript">

    // $(document).ready(function(){
    //     $('#jumlah_kamar').autoNumeric();
    // });

    var tanpa_rupiah = document.getElementById('jumlah_kamar');
    tanpa_rupiah.addEventListener('keyup', function(e)
    {
        tanpa_rupiah.value = formatRupiah(this.value);
    });
    
    tanpa_rupiah.addEventListener('keydown', function(event)
    {
        limitCharacter(event);
    });

    //Fungsinya
    function formatRupiah(bilangan, prefix)
    {
        var number_string = bilangan.replace(/[^,\d]/g, '').toString(),
            split   = number_string.split(','),
            sisa    = split[0].length % 3,
            rupiah  = split[0].substr(0, sisa),
            ribuan  = split[0].substr(sisa).match(/\d{1,3}/gi);
            
        if (ribuan) {
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }
        
        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return prefix == undefined ? rupiah : (rupiah ? 'Rp. ' + rupiah : '');
    }
    
    function limitCharacter(event)
    {
        key = event.which || event.keyCode;
        if ( key != 188 // Comma
             && key != 8 // Backspace
             && key != 17 && key != 86 & key != 67 // Ctrl c, ctrl v
             && (key < 48 || key > 57) // Non digit
             // Dan masih banyak lagi seperti tombol del, panah kiri dan kanan, tombol tab, dll
            ) 
        {
            event.preventDefault();
            return false;
        }
    }

</script>
@endsection

resources/views/kost/form.blade.php
<div class="form-group row">
	{!! Form::label('nama_kost','Nama Kost :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
	{!! Form::text('nama_kost',null, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group row">
	{!! Form::label('jenis_kost','Satuan :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
	{!! Form::select('jenis_kost', ['Pria' => 'Pria', 'Wanita' => 'Wanita', 'Campur' => 'Campur'], null, ['placeholder' => 'Jenis kost...', 'class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group row">
	{!! Form::label('kamar_mandi','Kamar Mandi :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
	{!! Form::select('kamar_mandi', ['Luar' => 'Luar', 'Dalam' => 'Dalam'], null, ['placeholder' => 'Kamar mandi...', 'class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group row">
	{!! Form::label('foto', 'Foto :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
  	{!! Form::file('foto',null, ['class' => 'form-control']) !!}
  	</div>
</div>

<div class="form-group row">
	{!! Form::label('alamat_kost','Alamat :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
	{!! Form::textarea('alamat_kost',null, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group row">
	{!! Form::label('deskripsi','Deskripsi Kos :', ['class' => 'col-lg-2 control-label']) !!}
	<div class="col-lg-10">
	{!! Form::textarea('deskripsi',null, ['class' => 'form-control']) !!}
	</div>
</div>

<div class="form-group row">
	{!! Form::submit(isset($model) ? 'Ubah' : 'Simpan', ['class'=>'btn btn-primary']) !!}
</div>

resources/views/kost/index.blade.php
@extends('layouts.admin')

@section('content')
<br>

@if (session('sukses'))
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Selamat!</strong> {{ session('sukses') }}
</div>
@elseif (session('gagal'))
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Oops!</strong> {{ session('gagal') }}
</div>
@endif

<div class="row">
    <div class="col-lg-12">
    <h3>Tabel Data Kost</h3>
    <div class="btn-group">
        <a href="{{route ('kost.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> Tambah Kost</a>
    </div>
    <hr>
        <div class="card card-accent-primary">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Data Kost
            </div>
            <div class="card-block">
                <form action="{{ url('carikost') }}" method="POST">{!! csrf_field() !!}
                    <div class="input-group">
                        <input type="text" name="cari" class="form-control" placeholder="Cari kost berdasarkan nama">
                        <span class="input-group-btn">
                            <button class="btn btn-primary">
                                <i class="fa fa-search"> Cari</i>
                            </button>
                        </span>
                    </div>
                </form>
                <br>
                <table class="table">
					<thead class="thead-inverse">
						<tr>
							<th>Nama Kost</th>
							<th>Status</th>
							<th>Nama Pemilik</th>
							<th>Jenis Kost</th>
							<th>Kamar Mandi</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($kost as $kost)
						<tr id="{{ $kost->id }}">
							<td>{{$kost->nama_kost}}</td>
							<td>
								@if($kost->status=='Disetujui')
								<button class="btn btn-sm btn-block btn-success">
									<i class="fa fa-check"></i> Disetujui
								</button>
								@else
								<button class="btn btn-sm btn-block btn-secondary">
									<i class="fa fa-hourglass"></i> Proses
								</button>
								@endif
							</td>
							<td>{{$kost->user->nama_depan}}</td>
							<td>{{$kost->jenis_kost}}</td>
							<td>{{$kost->kamar_mandi}}</td>
							<td>
								<a href="{{route('kost.show', $kost->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-eye">Lihat</i></a>
								<a href="{{route('kost.edit', $kost->id)}}" class="btn btn-sm btn-warning"><i class="fa fa-edit">Ubah</i></a>
								<button name="delete" class="btn btn-sm btn-danger">
									<i class="fa fa-trash-o">Hapus</i>
								</button>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@section('modal')
    <div id="delete" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" role="form" method="POST" action="{{ url('/kost') }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="id" value="">

                    <div class="modal-header">
                        <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Hapus Kost</h4>
                    </div>

                    <div class="modal-body">
                        <p>
                            Apakah Anda yakin ingin menghapus kost ini?
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" name="batal">
                            <i class="fa fa-btn fa-ban"></i> Batal
                        </button>
                        <button type="submit" class="btn btn-success" name="simpan">
                            <i class="fa fa-btn fa-trash"></i> Hapus
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <!-- My App -->
    <script type="text/javascript">
        $(document)
        
        .on('click', 'button[name="delete"]', function() {
            var id = $(this).parents('tr').first().attr('id');
            $('#delete input[name="id"]').val(id);
            $('#delete').removeClass('fade');
            $('#delete').show();
        })

        .on('click', 'button[name="batal"], .close-modal', function() {
            $('.modal').hide();
            $('.modal input[name="id"]').val('');
        })
        ;
    </script>
@endsection