app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return redirect('/login');
});

// Daftar Route
Route::get('/register', 'AuthController@register');
Route::post('/register', 'AuthController@postRegister');

//Login Route
Route::get('/login', 'AuthController@login');
Route::post('/handleLogin', 'AuthController@handleLogin');
Route::get('/logout', 'AuthController@logout');

// Reset Password
Route::get('password/reset/{token?}', 'PasswordController@showResetForm');
Route::post('password/email', 'PasswordController@sendResetLinkEmail');
Route::post('password/reset', 'PasswordController@reset');
Route::get('formatid', 'PesanController@pesanID');


Route::group(['middleware' => 'auth'], function() {
	Route::get('/home', 'HomeController@index');
	Route::get('/profil', 'HomeController@profil');
	Route::post('/foto_profil', 'AuthController@foto_profil');
	Route::get('/ubah_profil', 'HomeController@ubah_profil');
	Route::post('/update_profil', 'HomeController@update_profil');
	Route::post('/gantipassword', 'AuthController@gantipassword');
	Route::get('/detail/{detail}', 'HomeController@detail_kost');
	Route::get('/listkost/{gender}', 'HomeController@listkost');
	Route::post('/testimoni', 'HomeController@testimoni');
	Route::delete('/testimoni', 'HomeController@hapusTestimoni');
	Route::get('/addkost', 'PemilikController@add_mykost');
	Route::get('/unduh', 'HomeController@unduh');
	/* ---ADMINISTRATOR--- */
	Route::group(['middleware' => 'role:admin'], function() 
	{
		Route::get('/admin', 'AdminController@beranda');
		
		/* ---PARAMETER/VARIABEL ROUTE--- */
		Route::get('/parameter','ParameterController@index');
		Route::post('/parameter','ParameterController@store');
		Route::put('/parameter','ParameterController@update');
		Route::delete('/parameter','ParameterController@destroy');

		/* ---HIMPUNAN ROUTE--- */
		Route::get('/himpunan','HimpunanController@index');
		Route::post('/himpunan','HimpunanController@store');
		Route::put('/himpunan','HimpunanController@update');
		Route::delete('/himpunan','HimpunanController@destroy');

		/* ---DERAJAT KEANGGOTAAN ROUTE--- */
		Route::get('/derajat','DerajatController@index');
		Route::get('/derajat/generate','DerajatController@generate');

		/* ---PENGGUNA ROUTE--- */
		Route::get('/pengguna/{level}', 'UserController@user');
		Route::resource('/user','UserController');
		Route::delete('/user','UserController@destroy');

		/* ---KOSTAN ROUTE--- */
		Route::resource('/kost','KostController');
		Route::delete('/kost','KostController@destroy');
		Route::post('/carikost','KostController@carikost');

		/* ---PEMESANAN ROUTE--- */
		Route::get('/pesan','PesanController@index');
	});

	/* ---PEMILIK--- */
	Route::group(['middleware' => 'role:pemilik'], function() 
	{
		Route::get('/kostsaya', 'PemilikController@kostsaya');
		Route::post('/storekost', 'PemilikController@storekost');
		Route::get('/lengkapi/{kost}', 'PemilikController@lengkapi');
		Route::post('/lengkapi', 'PemilikController@postlengkapi');
		Route::get('/ubahkriteria/{id}', 'PemilikController@ubahkriteria');
		Route::get('/edit_kost/{id}', 'PemilikController@edit_kost');
		Route::post('/update_kost', 'PemilikController@update_kost');
		Route::delete('/hapuskost', 'PemilikController@hapuskost');
	});

	/* ---MAHASISWA--- */
	Route::group(['middleware' => 'role:mahasiswa|admin'], function()
	{
		Route::post('/cari', 'HomeController@cari');
		Route::get('/pencarian', 'HomeController@pencarian');
		Route::post('/pesan','PesanController@store');
		Route::get('/pesan/{id}','PesanController@show');
		Route::delete('/pesan','PesanController@destroy');
	});

});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;


class User extends Model implements Authenticatable, CanResetPasswordContract
{
    use \Illuminate\Auth\Authenticatable;
    use CanResetPassword;
    
	public function kost()
    {
    	return $this->hasMany('App\Kost', 'user_id');
    }

    public function pesan()
    {
    	return $this->hasMany('App\Pesan', 'user_id');
    }

    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php 

namespace App\Http\Controllers;

use App\User;
use App\Level;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Image;
use Storage;
use Hash;

/**
* 
*/
class UserController extends Controller
{
	public function index() {
		$users = User::where('level', 'admin')->get();
		return view('user.admin', compact('users'));
	}

	public function create()
	{
		return view('user.create',compact('level'));
	}

	public function store(Request $request)
	{
		$this->validate($request, [
            'no_identitas' => 'required|max:225',
            'nama_depan' => 'required|max:225',
            'nama_belakang' => 'required|max:225',
            'email' => 'required|email|unique:users|max:225',
            'username' => 'required|unique:users|max:225',
            'jenis' => 'required',
            'hp' => 'required|max:20',
        ]);

		$user = new User();
		$user->no_identitas = Input::get('no_identitas');
		$user->nama_depan = Input::get('nama_depan');
		$user->nama_belakang = Input::get('nama_belakang');
		$user->email = Input::get('email');
		$user->username = Input::get('username');
		$user->password = Hash::make($user->no_identitas);
		$user->level = 'admin';
		$user->jenis = Input::get('jenis');
		$user->hp = Input::get('hp');
		$user->foto = 'user.png';

		$user->save();

		if ($user) {
            return redirect('user')->with('sukses', 'Selamat, anda berhasil menambah admin');
        } else {
            return redirect('user')->with('gagal', 'Maaf, terjadi kesalahan saat menambah.');
        }

	}

	public function show($id) {
		$user = User::find($id);
		return view('user.view', compact('user'));
	}

	public function edit($id) {
		$user = User::find($id);
		return view('user.update', compact('level', 'user'));
	}

	public function update(Request $request ,$id) {
		$user = User::find($id);
		$user->no_identitas = $request['no_identitas'];
		$user->nama_depan = $request['nama_depan'];
		$user->nama_belakang = $request['nama_belakang'];
		$user->email = $request['email'];
		$user->username = $request['username'];
		$user->jenis = $request['jenis'];
		$user->hp = $request['hp'];

		if ($user->update()) {
            return redirect()->back()->with('sukses', 'Selamat, anda berhasil meghapus admin');
        } else {
            return redirect()->back()->with('gagal', 'Maaf, terjadi kesalahan saat mengubah.');
        }
	}

	public function destroy(Request $request) {
		$user = User::find($request->id);
		Storage::delete('user_image/'.$user->foto);
		
		if ($user->delete()) {
            return redirect()->back()->with('sukses', 'Selamat, anda berhasil meghapus admin');
        } else {
            return redirect()->back()->with('gagal', 'Maaf, terjadi kesalahan saat menghapus.');
        }
	}

	public function user($level) {
		$users = User::where('level', $level)->get();
		return view('user.index', compact('users','level'));
	}

}

 ?>

resources/views/user/admin.blade.php
@extends('layouts.admin')

@section('content')
<br>
@if (session('sukses'))
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Selamat!</strong> {{ session('sukses') }}
</div>
@elseif (session('gagal'))
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Oops!</strong> {{ session('gagal') }}
</div>
@endif

<div class="row">
    <div class="col-lg-12">
    <h3>Tabel Data Admin</h3>
    <div class="btn-group">
        <a href="{{route ('user.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> Tambah Admin</a>
    </div>
    <hr>
        <div class="card card-accent-primary">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Data Administrator
            </div>
            <div class="card-block">
                <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th>No Identitas</th>
                            <th>Nama </th>
                            <th>Email </th>
                            <th>No HP </th>
                            <th>Aksi </th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($users as $user)
                        <tr id="{{ $user->id }}">
                            <td>{{$user->no_identitas}}</td>
                            <td>{{$user->nama_depan}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->hp}}</td>
                            <td>
                                <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-eye">Lihat</i></a>
                                <button type="button" name="delete" class="btn btn-sm btn-danger btn-xs"><i class="fa fa-trash">Hapus</i>
                                </button>
                            </td>
                        </tr>
                     @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--/col-->
</div>
@endsection

@section('modal')
    <div id="delete" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" role="form" method="POST" action="{{ url('/user') }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="id" value="">

                    <div class="modal-header">
                        <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Hapus Pengguna</h4>
                    </div>

                    <div class="modal-body">
                        <p>
                            Apakah Anda yakin ingin menghapus pengguna ini?
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" name="batal">
                            <i class="fa fa-btn fa-ban"></i> Batal
                        </button>
                        <button type="submit" class="btn btn-success" name="simpan">
                            <i class="fa fa-btn fa-trash"></i> Hapus
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <!-- My App -->
    <script type="text/javascript">        
        $(document)
        
        .on('click', 'button[name="delete"]', function() {
            var id = $(this).parents('tr').first().attr('id');
            $('#delete input[name="id"]').val(id);
            $('#delete').removeClass('fade');
            $('#delete').show();
        })

        .on('click', 'button[name="batal"], .close-modal', function() {
            $('.modal').hide();
            $('.modal input[name="id"]').val('');
        })
        ;
    </script>
@endsection

resources/views/user/create.blade.php
@extends('layouts.admin')

@section('content')
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Tambah User</strong> Isi identitas user
            </div>
            <div class="card-block">
                {!! Form::open(['route' => 'user.store', 'files' => true, 'class' => 'form-horizontal'])!!}

                    <div class="form-group row {{ $errors->has('no_identitas') ? ' has-danger' : '' }}">
                        <label for="no_identitas" class="col-lg-2 control-label">No. Identitas</label>
                        <div class="col-lg-10">
                            <input name="no_identitas" type="text" class="form-control" id="no_identitas" placeholder="NIM, KTP, SIM " value="{{ old('no_identitas') }}">
                            @if ($errors->has('no_identitas'))
                            <div class="form-control-feedback">
                                {{ $errors->first('no_identitas') }}
                            </div>
                            @endif
                        </div>

                    </div>

                    <div class="form-group row {{ $errors->has('nama_depan') ? ' has-danger' : '' }}">
                        <label for="nama_depan" class="col-lg-2 control-label">Nama Depan</label>
                        <div class="col-lg-10">
                            <input name="nama_depan" type="text" class="form-control" id="nama_depan" placeholder="Nama Depan" value="{{ old('nama_depan') }}">
                            @if ($errors->has('nama_depan'))
                            <div class="form-control-feedback">
                                {{ $errors->first('nama_depan') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('nama_belakang') ? ' has-danger' : '' }}">
                        <label for="nama_belakang" class="col-lg-2 control-label">Nama Belakang</label>
                        <div class="col-lg-10">
                            <input name="nama_belakang" type="text" class="form-control" id="nama_belakang" placeholder="Nama Belakang" value="{{ old('nama_belakang') }}">
                            @if ($errors->has('nama_belakang'))
                            <div class="form-control-feedback">
                                {{ $errors->first('nama_belakang') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('jenis') ? ' has-danger' : '' }}">
                    <label for="jenis" class="col-lg-2 control-label">Jenis Kelamin</label>
                        <div class="col-lg-10">
                            <select name="jenis" class="form-control" id="jenis">
                                <option>--Pilih jenis kelamin--</option>
                                <option value="Pria" {{ (old('jenis') == 'Pria' ? "selected":"") }}>Pria</option>
                                <option value="Wanita" {{ (old('jenis') == 'Wanita' ? "selected":"") }}>Wanita</option>
                            </select>
                            @if ($errors->has('jenis'))
                            <div class="form-control-feedback">
                                {{ $errors->first('jenis') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('email') ? ' has-danger' : '' }}">
                        <label for="email" class="col-lg-2 control-label">Alamat Email</label>
                        <div class="col-lg-10">
                            <input name="email" type="text" class="form-control" id="email" placeholder="Alamat Email" value="{{ old('email') }}">
                            @if ($errors->has('email'))
                            <div class="form-control-feedback">
                                {{ $errors->first('email') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('username') ? ' has-danger' : '' }}">
                        <label for="username" class="col-lg-2 control-label">Username</label>
                        <div class="col-lg-10">
                            <input name="username" type="text" class="form-control" id="username" placeholder="Username" value="{{ old('username') }}">
                            @if ($errors->has('username'))
                            <div class="form-control-feedback">
                                {{ $errors->first('username') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('hp') ? ' has-danger' : '' }}">
                        <label for="hp" class="col-lg-2 control-label">No Telepon</label>
                        <div class="col-lg-10">
                            <input name="hp" type="number" class="form-control" id="hp" placeholder="No Telepon" value="{{ old('hp') }}">
                            @if ($errors->has('hp'))
                            <div class="form-control-feedback">
                                {{ $errors->first('hp') }}
                            </div>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row {{ $errors->has('level') ? ' has-danger' : '' }}">
                        <label for="hp" class="col-lg-2 control-label">Hak Akses</label>
                        <div class="col-lg-10">
                            <input name="level" type="text" class="form-control" id="level" value="Admin" disabled="true">
                        </div>
                    </div>
             
                    <div class="form-group row">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="reset" class="btn btn-default">Batal</button>
                            <button type="submit" class="btn btn-success">Simpan</button>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.admin')

@section('content')
<br>
@if (session('sukses'))
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Selamat!</strong> {{ session('sukses') }}
</div>
@elseif (session('gagal'))
<div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>Oops!</strong> {{ session('gagal') }}
</div>
@endif

<div class="row">
    <div class="col-lg-12">
    @if($level == 'mahasiswa')
    <h3>Tabel Data Mahasiswa</h3>
    @else
    <h3>Tabel Data Pemilik</h3>
    @endif
    <hr>
        <div class="card card-accent-primary">
            <div class="card-header">
                @if($level == 'mahasiswa')
                <i class="fa fa-align-justify"></i> Data Mahasiswa
                @else
                <i class="fa fa-align-justify"></i> Data Pemilik
                @endif
            </div>
            <div class="card-block">
                <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th>No Identitas</th>
                            <th>Nama </th>
                            <th>Email </th>
                            <th>No HP </th>
                            <th>Aksi </th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($users as $user)
                        <tr id="{{ $user->id }}">
                            <td>{{$user->no_identitas}}</td>
                            <td>{{$user->nama_depan}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->hp}}</td>
                            <td>
                                <a href="{{route('user.show', $user->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-eye">Lihat</i></a>
                                <button type="button" name="delete" class="btn btn-sm btn-danger btn-xs"><i class="fa fa-trash">Hapus</i>
                                </button>
                            </td>
                        </tr>
                     @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--/col-->
</div>
@endsection

@section('modal')
    <div id="delete" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form class="form-horizontal" role="form" method="POST" action="{{ url('/user') }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="id" value="">

                    <div class="modal-header">
                        <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title">Hapus Pengguna</h4>
                    </div>

                    <div class="modal-body">
                        <p>
                            Apakah Anda yakin ingin menghapus pengguna ini?
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" name="batal">
                            <i class="fa fa-btn fa-ban"></i> Batal
                        </button>
                        <button type="submit" class="btn btn-success" name="simpan">
                            <i class="fa fa-btn fa-trash"></i> Hapus
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <!-- My App -->
    <script type="text/javascript">        
        $(document)
        
        .on('click', 'button[name="delete"]', function() {
            var id = $(this).parents('tr').first().attr('id');
            $('#delete input[name="id"]').val(id);
            $('#delete').removeClass('fade');
            $('#delete').show();
        })

        .on('click', 'button[name="batal"], .close-modal', function() {
            $('.modal').hide();
            $('.modal input[name="id"]').val('');
        })
        ;
    </script>
@endsection

resources/views/user/update.blade.php
@extends('layouts.admin')

@section('content')
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Ubah User</strong> Isi identitas baru user
            </div>
            <div class="card-block">
                {!! Form::model($user, ['route' => ['user.update', $user], 'method' =>'patch', 'files' => true, 'class' => 'form-horizontal'])!!}
                    <fieldset>
                        <div class="form-group row">
                            <label for="no_identitas" class="col-lg-2 control-label">No. Identitas</label>
                            <div class="col-lg-10">
                                <input name="no_identitas" type="text" class="form-control" value="{{$user->no_identitas}}" placeholder="NIM, KTP, SIM ">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nama_depan" class="col-lg-2 control-label">Nama Depan</label>
                            <div class="col-lg-10">
                                <input name="nama_depan" type="text" class="form-control" value="{{$user->nama_depan}}" placeholder="Nama Depan">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nama_belakang" class="col-lg-2 control-label">Nama Belakang</label>
                            <div class="col-lg-10">
                                <input name="nama_belakang" type="text" class="form-control" value="{{$user->nama_belakang}}" placeholder="Nama Belakang">
                            </div>
                        </div>

                        <div class="form-group row">
                        <label for="jenis" class="col-lg-2 control-label">Jenis Kelamin</label>
                            <div class="col-lg-10">
                                <select name="jenis" class="form-control" id="jenis">
                                    <option></option>
                                    <option value="Pria">Pria</option>
                                    <option value="Wanita">Wanita</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-lg-2 control-label">Alamat Email</label>
                            <div class="col-lg-10">
                                <input name="email" type="text" class="form-control" value="{{$user->email}}" placeholder="Alamat Email">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="username" class="col-lg-2 control-label">Username</label>
                            <div class="col-lg-10">
                                <input name="username" type="text" class="form-control" value="{{$user->username}}" placeholder="Username">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="hp" class="col-lg-2 control-label">No Telepon</label>
                            <div class="col-lg-10">
                                <input name="hp" type="number" class="form-control" value="{{$user->hp}}" placeholder="No Telepon">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-10 col-lg-offset-2">
                                <button type="reset" class="btn btn-danger">Batal</button>
                                <button type="submit" class="btn btn-success">Simpan</button>
                            </div>
                        </div>
                    </fieldset>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection     

resources/views/user/view.blade.php
@extends('layouts.admin')
@section('content')
<br>
<div class="row">
	<div class="card">
        <div class="card-header">
            <i class="fa fa-user"></i> Data Pengguna</div>
        <div class="card-block">
	        <div class="col-sm-3">
	            <img src="{{URL::to('/user_image/'.$user->foto)}}" width="100%">
	        </div>
	        <div class="col-sm-9"> 
	            <dl class="row">
	                <dt class="col-sm-3">ID User</dt>
	                <dd class="col-sm-9">{{$user->id}}</dd>

	                <dt class="col-sm-3">No Identitas</dt>
	                <dd class="col-sm-9">{{$user->no_identitas}}</dd>

	                <dt class="col-sm-3">Nama Depan</dt>
	                <dd class="col-sm-9">{{$user->nama_depan}}</dd>

	                <dt class="col-sm-3">Nama Belakang</dt>
	                <dd class="col-sm-9">{{$user->nama_belakang}}</dd>

	                <dt class="col-sm-3">Jenis Kelamin</dt>
	                <dd class="col-sm-9">{{$user->jenis}}</dd>

	                <dt class="col-sm-3">Username</dt>
	                <dd class="col-sm-9">{{$user->username}}</dd>

	                <dt class="col-sm-3">Email</dt>
	                <dd class="col-sm-9">{{$user->email}}</dd>

	                <dt class="col-sm-3">No Telpon</dt>
	                <dd class="col-sm-9">{{$user->hp}}</dd>

	                <dt class="col-sm-3">Username</dt>
	                <dd class="col-sm-9">{{$user->username}}</dd>

	                <dt class="col-sm-3">Sebagai</dt>
	                <dd class="col-sm-9">{{$user->level}}</dd>
	            </dl>
	        </div>
	    </div>
    </div>
</div>
@endsection